server:
  port:8080
spring:
  application:
    name: gateway-service
  security:
    oauth2:
      client:
        provider:
          google:
            issuer-uri: https://accounts.google.com
        registration:
          google:
            client-id: 595330427883-316u8s61o5v65urpv8kfokbbmc16gb76.apps.googleusercontent.com
            client-secret: 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
            scope: openid
            redirect_uri: http://gateway-service:8080/login/oauth2/code/google
  sleuth:
    sampler:
    probability: 1.0
  zipkin:
    baseUrl: http://zipkin:9411/
    enabled: true

  cloud:
    gateway:
      default-filters:
        - TokenRelay
        - LogFilter
      routes:
        - id: accountRoute #Identificador de la ruta
          uri: http://gateway-service:8080/
          predicates: # Reglas de analisis de request
            - Path=/account/**
        # Routeo del primer microservicio
        - id: movie-service
          uri: lb://movie-service
          predicates:
            - Path=/movies/**
          filters:
            - AddRequestHeader=user-request-header, custom-user-request-header
            - AddResponseHeader=user-response-header, custom-user-response-header
        # Routeo del segundo microservicio
        - id: catalog-service
          uri: lb://catalog-service
          predicates:
            - Path=/catalog/**
          filters:
            - AddRequestHeader=user-request-header, custom-user-request-header
            - AddResponseHeader=user-response-header, custom-user-response-header
        # Routeo del tercer microservicio
        - id: serie-service
          uri: lb://serie-service
          predicates:
            - Path=/series/**
          filters:
            - AddRequestHeader=user-request-header, custom-user-request-header
            - AddResponseHeader=user-response-header, custom-user-response-header

eureka:
  instance:
    hostname: eureka-server
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefered-ip-address: true
  client:
    registry-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka