server:
  port : 8081
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  sleuth:
    sampler:
    probability: 1.0
  #Cambiando el hostname por el que levanta el docker-compose.yml
  zipkin:
    baseUrl: http://zipkin:9411/zipkin
    enabled: true
  # db -> Se modifico el hostname y las contraseñas que previamente setee dentro del contenedor que builde dentro del docker-compose.yml
  datasource:
    url: jdbc:mysql://db-mysql:3306/movies 
    username: user
    password: 12345
  rabbitmq:
    host: rabbit-mq 
    port: 5672
    username: guest
    password: guest
queue:
  movie:
    name: queueMovie
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
      fetch-registry: true
      register-with-eureka: true