server:
  port : 8083
spring:
  application:
    name: serie-service
  data:
    mongodb:
      host: db-mongo
      port: 27017
      database: backendExamen
  sleuth:
    sampler:
    probability: 1.0
  zipkin:
    baseUrl: http://zipkin:9411/
    enabled: true
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

queue:
  serie:
    name: queueSerie  
    
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always